export const PLAN_LIMITS = {
  FREE: {
    maxSocialAccounts: 5,
    maxPostsPerMonth: 50,
    maxTeamMembers: 1,
    maxClients: 3,
    analyticsHistoryDays: 7,
    watermarkEnabled: true,
    whiteLabelEnabled: false,
    apiAccessEnabled: false,
    bulkSchedulingEnabled: false,
    perPlatformEditorEnabled: false,
    autoResponder: 'none' as const,
    allowedPlatforms: ['FACEBOOK', 'INSTAGRAM'],
    twitterEnabled: false,
    automationEnabled: false,
  },
  STARTER: {
    maxSocialAccounts: 10,
    maxPostsPerMonth: 200,
    maxTeamMembers: 1,
    maxClients: 10,
    analyticsHistoryDays: 30,
    watermarkEnabled: false,
    whiteLabelEnabled: false,
    apiAccessEnabled: false,
    bulkSchedulingEnabled: false,
    perPlatformEditorEnabled: false,
    autoResponder: 'basic' as const,
    allowedPlatforms: ['FACEBOOK', 'INSTAGRAM', 'LINKEDIN'],
    twitterEnabled: false,
    automationEnabled: false,
  },
  GROWTH: {
    maxSocialAccounts: 30,
    maxPostsPerMonth: 2000,
    maxTeamMembers: 5,
    maxClients: 999999,
    analyticsHistoryDays: 180,
    watermarkEnabled: false,
    whiteLabelEnabled: false,
    apiAccessEnabled: false,
    bulkSchedulingEnabled: true,
    perPlatformEditorEnabled: true,
    autoResponder: 'advanced' as const,
    allowedPlatforms: ['FACEBOOK', 'INSTAGRAM', 'LINKEDIN', 'TWITTER', 'TIKTOK'],
    twitterEnabled: true,
    automationEnabled: true,
  },
  AGENCY_PRO: {
    maxSocialAccounts: 100,
    maxPostsPerMonth: 10000,
    maxTeamMembers: 15,
    maxClients: 999999,
    analyticsHistoryDays: 365,
    watermarkEnabled: false,
    whiteLabelEnabled: true,
    apiAccessEnabled: true,
    bulkSchedulingEnabled: true,
    perPlatformEditorEnabled: true,
    autoResponder: 'full' as const,
    allowedPlatforms: ['FACEBOOK', 'INSTAGRAM', 'LINKEDIN', 'TWITTER', 'TIKTOK', 'YOUTUBE'],
    twitterEnabled: true,
    automationEnabled: true,
  },
} as const;

export type PlanName = keyof typeof PLAN_LIMITS;
export type PlanLimitsType = typeof PLAN_LIMITS[PlanName];

export function getPlanLimits(plan: string): PlanLimitsType {
  return PLAN_LIMITS[plan as PlanName] || PLAN_LIMITS.FREE;
}
