[phases.setup]
nixPkgs = ["nodejs_18", "openssl"]

[phases.install]
cmds = ["npm install -g pnpm", "pnpm install --no-frozen-lockfile --filter api"]

[phases.build]
cmds = ["npx prisma generate", "pnpm run build"]

[start]
cmd = "npx prisma migrate deploy && node dist/main.js"
